### ISSUE TITLE
Add notification for when a student enqueues

### ISSUE THREAD

**Issue by JDierberger1** [debkbanerji/office-hours-queue#14]
Add a sound effect, when a student enqueues on an empty queue so TAs can know if they aren't watching the screen. Only make it ding when adding to an empty queue tho otherwise it will get rather annoying.

**Comment by debkbanerji** [comment]
Cool idea, but closed due to the conversation we had with Farhan last semester. The T.A.s should hopefully be frequently checking the queue anyway, - also, setting up speakers would be a pain.

Forgot to close this earlier - sorry about that.
